### ISSUE TITLE
Terminal-kit is a private npm module

### ISSUE THREAD

**Issue by jgentes** [bsorrentino/copilot-cli-agent#4]
Doing an `npm install` results in `npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@bsorrentino/terminal-kit/3.0.1-build16/e3555d16e8d9c56e01a8040c5e7e7f2e57181d14 - authentication token not provided`

Looks like you have a private package in there. Is there a fair oss equivalent?

Thanks for putting this repo together!

**Comment by bsorrentino** [comment]
Hi @jgentes  thanks for feedback I'll fix this asap

**Comment by bsorrentino** [comment]
Hi @jgentes  the `terminal-kit` package is now public. keep in mind that it is a experimental fork. I suggest to use `simple-cli` package to test application

**Comment by jgentes** [comment]
Hi @bsorrentino sorry for the delay, been traveling. Looks like there is no public `https://www.npmjs.com/package/@bsorrentino/terminal-kit`

**Comment by bsorrentino** [comment]
Hi @jgentes thanks for feedback

the package [@bsorrentino/terminal-kit@3.0.1-build16 ](https://github.com/users/bsorrentino/packages/npm/package/terminal-kit) is a my experimentation and it is exclusively deployed as [github npm package](https://docs.github.com/articles/configuring-npm-for-use-with-github-package-registry/)

> ⚠️Since the terminal-kit module is just an experiment you can also avoid to build it ⚠️

**Comment by jgentes** [comment]
I see, I think I had something wrong with my `package-lock.json` file, looks like it's working - thanks!
